matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      language: c
      compiler: gcc
      script: make -f makefile.unix
      before_install:
      - sudo apt update -qq
      - sudo apt install -qq make automake build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb++-dev libminiupnpc-dev libboost-all-dev libqrencode-dev libcurl4-gnutls-dev libminizip-dev
      - cd src/
    # - os: osx
      # osx_image: xcode9.2
      # script: make -f makefile.osx
      # sudo: required
      # language: c
      # before_install:
      # - export COLUMNS=80
      # - curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      # - chmod +x ./macports-ci
      # - ./macports-ci install
      # - PATH="/opt/local/bin:$PATH"
      # - sudo port -N install boost db48 openssl miniupnpc minizip curl
      # - cd src/

